# -*- coding: utf-8 -*-
"""1_cycle2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RaQMx_cDAvd3QR6PjMUYwFTVs5mo0DP3
"""

#Suppose a newly born pair of rabbits, one male and one female, are 
#put in a field. Rabbits can mate at the age of one month so that at the 
#end of its second month, a female has produced another pair of 
#rabbits. Suppose that our rabbits never die and that the female always 
#produces one new pair every month from the second month.
#Develop a program to show a table containing the number of pairs of 
#rabbits in the first N months.

def num_rabbits():
  n=int(input('Enter the number of months : ')) #reading number of months
  a = 0
  b = 1
  c=0
  print("\n\n")
  print("Months\t\tNo. of pair of rabbits")
  for i in range(1,n+1):                        #calculating number of pair of rabbits
    c = b                                       #it is fibinocci series
    b = a+b
    a = c
    print(i,"\t\t",a)

num_rabbits()